### ISSUE TITLE
Strange encoding issue

### ISSUE THREAD

**Issue by mkoczorowski** [judev/php-htmltruncator#12]
Hi, Firstly congratulations on the project. Its simply awesome!
However, I'm getting a strange a really strange issue and I ran out of options.
Default charset in php.ini is set to UTF-8, same symfony setting. 
When I get the data from db all is fine, but after running this trough htmltruncator the encoding is wrong and I'm getting weird characters.
![image](https://user-images.githubusercontent.com/8155896/54244091-f7328a80-4522-11e9-9633-ad8ffbd5e068.png)

any idea what may cause this ? Please help

**Comment by ajgagnon** [comment]
@mkoczorowski Did you figure out the cause of this? I'm having this issue too.
