### ISSUE TITLE
Problem with adjacent HTML tags

### ISSUE THREAD

**Issue by patkruk** [judev/php-htmltruncator#3]
Hey,

There seems to be a problem with adjacent HTML tags. 

For example, try to truncate this to 25 characters:
```html
<p>Lorem Ipsum</p><p>Lorem <div>Lorem Ipsum</div> Ipsum</p>
```
and check the output. You should notice an issue with the markdown. 

If I change the second paragraph to h1, everything seems to be fine.

**Comment by judev** [comment]
The DOM implementation will automatically add an ending `</p>` tag before the opening `<div>` which is why you're seeing this.

This is because `<div>` elements should not occur inside `<p>` elements:
http://stackoverflow.com/questions/8397852/why-p-tag-cant-contain-div-tag-inside-it

**Comment by patkruk** [comment]
Got it, thanks!
