### ISSUE TITLE
Require only stable versions

### ISSUE THREAD

**Issue by cdekok** [judev/php-htmltruncator#6]
Using version ^1.0 for judev/php-htmltruncator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - judev/php-htmltruncator 1.0.6 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.5 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.4 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.3 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.2 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.1 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - judev/php-htmltruncator 1.0.0 requires electrolinux/php-html5lib dev-master -> no matching package found.
    - Installation request for judev/php-htmltruncator ^1.0 -> satisfiable by judev/php-htmltruncator[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

**Comment by wesleywesley** [comment]
how to solve this ?

**Comment by wesleywesley** [comment]
added this to my own composer.json, fixes the issue for now: 

        "electrolinux/php-html5lib": "dev-master as 0.1.0",

**Comment by judev** [comment]
I've now updated `composer.json` to require `0.1.0` instead of `dev-master`
