### ISSUE TITLE
Problem with Unicode characters

### ISSUE THREAD

**Issue by dslaugh** [judev/php-htmltruncator#8]
When I run unicode characters through truncate it doesn't come through correctly

Expected:
<p>This is the greek letter beta: β</p>

Actual:
<p>This is the greek letter beta: Î²</p>

**Comment by judev** [comment]
Could you provide a minimal test case that shows this? I've added the `testUnicodeDoesntBreak` test with your sample text and it's working as it should. Thanks!

**Comment by ErwanTremiot** [comment]
Hi,

when I truncate unicode strings using the length_in_chars flag, it cuts to a wrong number of characters.
I think this comes from the use of strlen and substr.
Here is the input and expected strings I use in my tests:

- Input: Ячмень пивоваренный. Ячмень пивоваренный,  Ячмень пивоваренный; Ячмень пивоваренный.
- Expected: Ячмень пивоваренный. Ячмень пивоваренный, Ячмень

**Comment by judev** [comment]
Thanks for the info, I've just pushed up v1.1.0 which should improve things here. Truncation for the Russian text will require the [intl extension](http://php.net/intl). [mbstring](http://php.net/mbstring) is also recommended.

**Comment by ErwanTremiot** [comment]
Thanks for the correction, it works nice.
